<a href="https://colab.research.google.com/github/bsjin1122/deep-learning/blob/main/tensorflow/part02/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

print(tf.executing_eagerly())

True


In [5]:
a = 1
b = 2
c = tf.math.add(a, b)
print(c)
c.numpy()

tf.Tensor(3, shape=(), dtype=int32)


3

In [7]:
a = tf.constant(1)
b = tf.constant(2)
print("a:",a)
print("b:",b) # 32비트 정수형임을 확인할 수 있다.

a: tf.Tensor(1, shape=(), dtype=int32)
b: tf.Tensor(2, shape=(), dtype=int32)


In [8]:
# 랭크 확인
print(tf.rank(a))

tf.Tensor(0, shape=(), dtype=int32)


In [10]:
# 자료형 변환
a= tf.cast(a, tf.float32)
b= tf.cast(b, tf.float32)
print(a.dtype)
print(b.dtype)

<dtype: 'float32'>
<dtype: 'float32'>


In [11]:
# 덧셈
c = tf.math.add(a, b)
print("result: ", c)
print("rank: ", tf.rank(c))

result:  tf.Tensor(3.0, shape=(), dtype=float32)
rank:  tf.Tensor(0, shape=(), dtype=int32)


In [18]:
# 뺄셈
print(tf.math.subtract(a,b))

tf.Tensor(-1.0, shape=(), dtype=float32)


In [19]:
# 곱셈
print(tf.math.multiply(a,b))

tf.Tensor(2.0, shape=(), dtype=float32)


In [20]:
# 나눗셈
print(tf.math.divide(a,b))

tf.Tensor(0.5, shape=(), dtype=float32)


In [21]:
# 나눗셈(나머지)
print(tf.math.mod(a,b))

tf.Tensor(1.0, shape=(), dtype=float32)


In [22]:
# 나눗셈(몫)
print(tf.math.floordiv(a,b))

tf.Tensor(0.0, shape=(), dtype=float32)


In [25]:
import tensorflow as tf
import numpy as np

# 1차원 배열 정의
py_list = [10., 20., 30.] #python list
num_arr = np.array([10., 10., 10.]) # 넘파이 배열 활용

# 텐서 변환
vec1 = tf.constant(py_list, dtype=tf.float32)
vec2 = tf.constant(num_arr, dtype=tf.float32)

print("vec1: ", vec1)
print("vec2: ", vec2)

vec1:  tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
vec2:  tf.Tensor([10. 10. 10.], shape=(3,), dtype=float32)


In [26]:
# shape 속성은 (3,) 과 같이 1개의 축에 대해서만 크기가 표현. 1개의 축에 3개의 원소가 있다는 뜻이다.
# 텐서로 변환된 뒤에도 원본 배열의 실수형 속성이 그대로 유지.

In [27]:
#랭크 확인
print(tf.rank(vec1))
print(tf.rank(vec2))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [29]:
#덧셈함수
add1 = tf.math.add(vec1, vec2)
print("result:", add1)
print("rank: ", tf.rank(add1))

result: tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)
rank:  tf.Tensor(1, shape=(), dtype=int32)


In [30]:
# 덧셈 연산자
add2 = vec1 + vec2
print("result: ", add2)
print("rank: ", tf.rank(add2))

result:  tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)
rank:  tf.Tensor(1, shape=(), dtype=int32)


In [31]:
# tf.math 모듈 함수
print(tf.math.subtract(vec1, vec2))
print(tf.math.multiply(vec1, vec2))
print(tf.math.divide(vec1, vec2))
print(tf.math.mod(vec1, vec2))
print(tf.math.floordiv(vec1, vec2))

tf.Tensor([ 0. 10. 20.], shape=(3,), dtype=float32)
tf.Tensor([100. 200. 300.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [32]:
# 파이썬 연산자
print(vec1 - vec2)
print(vec1 * vec2)
print(vec1 / vec2)
print(vec1 % vec2)
print(vec1 // vec2)

tf.Tensor([ 0. 10. 20.], shape=(3,), dtype=float32)
tf.Tensor([100. 200. 300.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [33]:
# 합계 구하기
print ( tf.reduce_sum(vec1) )
print ( tf.reduce_sum(vec2) )

tf.Tensor(60.0, shape=(), dtype=float32)
tf.Tensor(30.0, shape=(), dtype=float32)


In [34]:
# 거듭제곱
print( tf.math.square(vec1) )

tf.Tensor([100. 400. 900.], shape=(3,), dtype=float32)


In [35]:
# 거듭제곱 (파이썬 연산자)
print( vec1**2 )

tf.Tensor([ 99.99999 400.      899.99994], shape=(3,), dtype=float32)


In [36]:
# 브로드캐스팅 연산
print (vec1 + 1)
# 백터의 형태를 유지한 상태에서 각 원소에 1을 더하게 된다.

tf.Tensor([11. 21. 31.], shape=(3,), dtype=float32)
