<a href="https://colab.research.google.com/github/bsjin1122/deep-learning/blob/main/part02/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

print(tf.executing_eagerly())

True


In [5]:
a = 1
b = 2
c = tf.math.add(a, b)
print(c)
c.numpy()

tf.Tensor(3, shape=(), dtype=int32)


3

In [7]:
a = tf.constant(1)
b = tf.constant(2)
print("a:",a)
print("b:",b) # 32비트 정수형임을 확인할 수 있다.

a: tf.Tensor(1, shape=(), dtype=int32)
b: tf.Tensor(2, shape=(), dtype=int32)


In [8]:
# 랭크 확인
print(tf.rank(a))

tf.Tensor(0, shape=(), dtype=int32)


In [10]:
# 자료형 변환
a= tf.cast(a, tf.float32)
b= tf.cast(b, tf.float32)
print(a.dtype)
print(b.dtype)

<dtype: 'float32'>
<dtype: 'float32'>


In [11]:
# 덧셈
c = tf.math.add(a, b)
print("result: ", c)
print("rank: ", tf.rank(c))

result:  tf.Tensor(3.0, shape=(), dtype=float32)
rank:  tf.Tensor(0, shape=(), dtype=int32)


In [18]:
# 뺄셈
print(tf.math.subtract(a,b))

tf.Tensor(-1.0, shape=(), dtype=float32)


In [19]:
# 곱셈
print(tf.math.multiply(a,b))

tf.Tensor(2.0, shape=(), dtype=float32)


In [20]:
# 나눗셈
print(tf.math.divide(a,b))

tf.Tensor(0.5, shape=(), dtype=float32)


In [21]:
# 나눗셈(나머지)
print(tf.math.mod(a,b))

tf.Tensor(1.0, shape=(), dtype=float32)


In [22]:
# 나눗셈(몫)
print(tf.math.floordiv(a,b))

tf.Tensor(0.0, shape=(), dtype=float32)


In [25]:
import tensorflow as tf
import numpy as np

# 1차원 배열 정의
py_list = [10., 20., 30.] #python list
num_arr = np.array([10., 10., 10.]) # 넘파이 배열 활용

# 텐서 변환
vec1 = tf.constant(py_list, dtype=tf.float32)
vec2 = tf.constant(num_arr, dtype=tf.float32)

print("vec1: ", vec1)
print("vec2: ", vec2)

vec1:  tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
vec2:  tf.Tensor([10. 10. 10.], shape=(3,), dtype=float32)


In [26]:
# shape 속성은 (3,) 과 같이 1개의 축에 대해서만 크기가 표현. 1개의 축에 3개의 원소가 있다는 뜻이다.
# 텐서로 변환된 뒤에도 원본 배열의 실수형 속성이 그대로 유지.

In [27]:
#랭크 확인
print(tf.rank(vec1))
print(tf.rank(vec2))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [29]:
#덧셈함수
add1 = tf.math.add(vec1, vec2)
print("result:", add1)
print("rank: ", tf.rank(add1))

result: tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)
rank:  tf.Tensor(1, shape=(), dtype=int32)


In [30]:
# 덧셈 연산자
add2 = vec1 + vec2
print("result: ", add2)
print("rank: ", tf.rank(add2))

result:  tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)
rank:  tf.Tensor(1, shape=(), dtype=int32)


In [31]:
# tf.math 모듈 함수
print(tf.math.subtract(vec1, vec2))
print(tf.math.multiply(vec1, vec2))
print(tf.math.divide(vec1, vec2))
print(tf.math.mod(vec1, vec2))
print(tf.math.floordiv(vec1, vec2))

tf.Tensor([ 0. 10. 20.], shape=(3,), dtype=float32)
tf.Tensor([100. 200. 300.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [32]:
# 파이썬 연산자
print(vec1 - vec2)
print(vec1 * vec2)
print(vec1 / vec2)
print(vec1 % vec2)
print(vec1 // vec2)

tf.Tensor([ 0. 10. 20.], shape=(3,), dtype=float32)
tf.Tensor([100. 200. 300.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [33]:
# 합계 구하기
print ( tf.reduce_sum(vec1) )
print ( tf.reduce_sum(vec2) )

tf.Tensor(60.0, shape=(), dtype=float32)
tf.Tensor(30.0, shape=(), dtype=float32)


In [34]:
# 거듭제곱
print( tf.math.square(vec1) )

tf.Tensor([100. 400. 900.], shape=(3,), dtype=float32)


In [35]:
# 거듭제곱 (파이썬 연산자)
print( vec1**2 )

tf.Tensor([ 99.99999 400.      899.99994], shape=(3,), dtype=float32)


In [36]:
# 브로드캐스팅 연산
print (vec1 + 1)
# 백터의 형태를 유지한 상태에서 각 원소에 1을 더하게 된다.

tf.Tensor([11. 21. 31.], shape=(3,), dtype=float32)


## 행렬

In [2]:
import tensorflow as tf

list_of_list = [[10, 20], [30, 40]]

# 텐서 변환 - constant 함수에 2차원 배열 입력
mat1 = tf.constant(list_of_list)

#랭크 확인
print("rank: ", tf.rank(mat1))

# 텐서 출력
print("mat1:",mat1)

rank:  tf.Tensor(2, shape=(), dtype=int32)
mat1: tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)


In [3]:
# 1차원 벡터 정의
vec1 = tf.constant([1, 0])
vec2 = tf.constant([-1, 2])

# 텐서 변환 - stack 함수로 1차원 배열을 위아래로 쌓기
mat2 = tf.stack([vec1, vec2])

# 랭크 확인
print("rank:", tf.rank(mat2))

# 텐서 출력하기
print("mat2:", mat2)

rank: tf.Tensor(2, shape=(), dtype=int32)
mat2: tf.Tensor(
[[ 1  0]
 [-1  2]], shape=(2, 2), dtype=int32)


In [4]:
# element-by-element 연산
element_mul = tf.math.multiply(mat1, mat2)
print("result:", element_mul)
print("rank:", tf.rank(element_mul))

result: tf.Tensor(
[[ 10   0]
 [-30  80]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [5]:
# 2차원 행렬에 스칼라 값인 3을 곱하면, 행렬의 모든 원소에 3을 곱하게 된다.
# 브로드캐스팅 연산
element_bc = tf.math.multiply(mat1, 3)
print("result:", element_bc)
print("rank:", tf.rank(element_bc))

result: tf.Tensor(
[[ 30  60]
 [ 90 120]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [6]:
# 행렬곱 연산
mat_mul = tf.matmul(mat1, mat2)
print("result:", mat_mul)
print("rank:", tf.rank(mat_mul))

result: tf.Tensor(
[[-10  40]
 [-10  80]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [7]:
# 덧셈 연산
add1 = tf.math.add(mat1, mat2)
print("result:", add1)
print("rank:", tf.rank(add1))

result: tf.Tensor(
[[11 20]
 [29 42]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [8]:
# 덧셈 연산자
add2 = mat1 + mat2
print("result:", add2)
print("rank:", tf.rank(add2))

result: tf.Tensor(
[[11 20]
 [29 42]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [9]:
# 텐서를 넘파이 배열로 변환
# nump() 메소드를 텐서 객체에 적용하면 된다.
np_arr = mat_mul.numpy()
print(type(np_arr))
print(np_arr)

<class 'numpy.ndarray'>
[[-10  40]
 [-10  80]]


## 고차원 텐서
- 1차원 벡터를 나열하면 2차원 행렬이 되고, 2차원 행렬을 나열하면 3차원 텐서가 된다.

In [10]:
# 라이브러리 불러오기
import tensorflow as tf
import numpy as np

# 2차원 배열 정의
mat1 = [[1, 2, 3, 4],
        [5, 6, 7, 8]]

mat2 = [[9, 10, 11, 12],
        [13, 14, 15, 16]]

mat3 = [[17, 18, 19, 20],
        [21, 22, 23, 24]]

# 텐서 변환 - constant 함수에 3차원 배열 입력
tensor1 = tf.constant([mat1, mat2, mat3])

# 랭크 확인
print("rank:", tf.rank(tensor1))

# 텐서 출력
print("tensor1:", tensor1)

rank: tf.Tensor(3, shape=(), dtype=int32)
tensor1: tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [11]:
# 텐서 변환 - stack 함수로 2차원 배열을 위아래로 쌓기
tensor2 = tf.stack([mat1, mat2, mat3])

# 랭크 확인
print("rank:", tf.rank(tensor2))

# 텐서 출력
print("tensor2:", tensor2)


rank: tf.Tensor(3, shape=(), dtype=int32)
tensor2: tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [12]:
# 1차원 배열 정의
vec1 = [1, 2, 3, 4]
vec2 = [5, 6, 7, 8]
vec3 = [9, 10, 11, 12]
vec4 = [13, 14, 15, 16]
vec5 = [17, 18, 19, 20]
vec6 = [21, 22, 23, 24]

# 1차원 배열을 원소로 갖는 2차원 배열 정의
arr = [[vec1, vec2],
        [vec3, vec4],
        [vec5, vec6]]

# 텐서 변환
tensor3 = tf.constant(arr)

# 랭크 확인
print("rank:", tf.rank(tensor3))

# 텐서 출력
print("tensor3:", tensor3)

rank: tf.Tensor(3, shape=(), dtype=int32)
tensor3: tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [13]:
# 랭크-4 텐서 만들기
tensor4 = tf.stack([tensor1, tensor2])

# 랭크 확인
print("rank:", tf.rank(tensor4))

# 텐서 출력
print("tensor4:", tensor4)

rank: tf.Tensor(4, shape=(), dtype=int32)
tensor4: tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]], shape=(2, 3, 2, 4), dtype=int32)


# 인덱싱

In [1]:
# 텐서플로 불러오기
import tensorflow as tf

# 벡터 정의하기
vec = tf.constant([10, 20, 30, 40, 50])
print(vec)

tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)


In [3]:
print(vec[0])
print(vec[-1])
print(vec[:3])


tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)
tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [4]:
# 행렬 정의하기
mat = tf.constant([[10, 20, 30],
                    [40, 50, 60]])

print(mat[0, 2])


tf.Tensor(30, shape=(), dtype=int32)


In [5]:
# 해당 열의 모든 행에 해당하는 원소를 갖는 벡터 추출
print(mat[:, 1])

tf.Tensor([20 50], shape=(2,), dtype=int32)


In [7]:
# 모든 행 모든 열 범위를 지정
print(mat[:, :])

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [8]:
# 랭크-3 텐서 정의하기
tensor = tf.constant([
    [[10, 20, 30],
     [40, 50, 60]],
    [[-10, -20, -30],
     [-40, -50, -60]],
])
print(tensor)

tf.Tensor(
[[[ 10  20  30]
  [ 40  50  60]]

 [[-10 -20 -30]
  [-40 -50 -60]]], shape=(2, 2, 3), dtype=int32)


In [9]:
# [인덱스0, 모든 인덱스, 모든 인덱스]
# 축 1방향으로 첫번째 원소인 (2, 3) 크기의 행렬을 먼저 찾고, 행렬의 모든 인덱스를 선택
print(tensor[0, :, :])

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [11]:
print(tensor[:, :2, :2])
# 축1 방향으로 모든 원소 선택, (2,3) 크기의 행렬 2개 선택
# 축(2, 3) 방향으로 :2, :2 범위로 슬라이싱 적용

tf.Tensor(
[[[ 10  20]
  [ 40  50]]

 [[-10 -20]
  [-40 -50]]], shape=(2, 2, 2), dtype=int32)


# 형태 변환

In [12]:
# 텐서플로 불러오기
import tensorflow as tf

# 랭크-1 텐서 정의하기
tensor = tf.constant(range(0, 24))
print(tensor)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)


In [13]:
# (3, 8) 형태의 행렬로 만들기
tensor1 = tf.reshape(tensor, [3, 8])
print(tensor1)

tf.Tensor(
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]], shape=(3, 8), dtype=int32)


In [14]:
tensor2 = tf.reshape(tensor1, [-1, 4]) #-1은 어떤 값이 되어도 관계없다는 뜻
# 먼저 값이 지정되어 있는 열의 크기인 4를 적용, 원소 개수와 배열의 형태에 따라 행의 크기르 ㄹ결정하게 된다.
print(tensor2)

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]], shape=(6, 4), dtype=int32)


In [16]:
# (24, ) 형태의 1차원 벡터로 변환
tensor3 = tf.reshape(tensor2, [-1])
print(tensor3)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)


In [17]:
tensor4 = tf.reshape(tensor3, [-1, 3, 4])
print(tensor4)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)


In [18]:
tensor5 = tf.reshape(tensor4, [3, 2, 4])
print(tensor5)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]], shape=(3, 2, 4), dtype=int32)


In [19]:
tensor6 = tf.reshape(tensor5, [3, 2, 2, 2])
print(tensor6)

tf.Tensor(
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]], shape=(3, 2, 2, 2), dtype=int32)


# 변수

In [20]:
# 텐서플로 불러오기
import tensorflow as tf

# 텐서 정의하기
tensor1 = tf.constant([[0, 1, 2],
                      [3, 4, 5]])
print(tensor1)

tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)


In [21]:
tensor_var1 = tf.Variable(tensor1)
print(tensor_var1)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]], dtype=int32)>


In [22]:
print("이름: ", tensor_var1.name)
print("크기: ", tensor_var1.shape)
print("자료형: ", tensor_var1.dtype)
print("배열: ", tensor_var1.numpy())

이름:  Variable:0
크기:  (2, 3)
자료형:  <dtype: 'int32'>
배열:  [[0 1 2]
 [3 4 5]]


In [23]:
# assign()메소드를 이용해 텐서플로 변수에 새로운 데이터를 할당
# 배열의 크기, 자료형이 원래 변수의 크기와 자료형이 동일해야 한다!

tensor_var1.assign([[1, 1, 1],
                    [2, 2, 2]])
print(tensor_var1)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]], dtype=int32)>


In [24]:
tensor2 = tf.convert_to_tensor(tensor_var1)
print(tensor2)

tf.Tensor(
[[1 1 1]
 [2 2 2]], shape=(2, 3), dtype=int32)


In [25]:
tensor_var2 = tf.Variable(tensor2, name='New Name')
print(tensor_var2.name)

New Name:0


In [26]:
tensor_var1 + tensor_var2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 2, 2],
       [4, 4, 4]], dtype=int32)>

# 자동 미분(Automatic Differentiation)

In [27]:
# 라이브러리 불러오기
import tensorflow as tf

# Y= 3X - 2 선형 관계를 갖는 데이터셋 생성
g = tf.random.Generator.from_seed(2020)
X = g.normal(shape=(10, ))
Y = 3 * X - 2

print('X: ', X.numpy())
print('Y: ', Y.numpy())

X:  [-0.20943771  1.2746525   1.213214   -0.17576954  1.876984    0.16379917
  1.082245    0.6199966  -0.4440221   1.3048344 ]
Y:  [-2.628313    1.8239574   1.6396422  -2.5273085   3.630952   -1.5086025
  1.2467351  -0.14001012 -3.3320663   1.9145031 ]


In [31]:
# Loss 함수 정의
def cal_mse(X, Y, a, b):

    Y_pred = a * X + b
    squared_error = (Y_pred - Y)**2
    mean_squared_error = tf.reduce_mean(squared_error)

    return mean_squared_error

In [29]:
# tf.GradientTape로 자동미분 과정을 기록

a = tf.Variable(0.0)
b = tf.Variable(0.0)

EPOCHS = 200

for epoch in range(1, EPOCHS + 1):

    with tf.GradientTape() as tape:
        mse = cal_mse(X, Y, a, b)

    grad = tape.gradient(mse, {'a': a, 'b': b})
    d_a, d_b = grad['a'], grad['b']

    a.assign_sub(d_a * 0.05)
    b.assign_sub(d_b * 0.05)

    if epoch % 20 == 0:
        print("EPOCH %d - MSE: %.4f --- a: %.2f --- b: %.2f" % (epoch, mse, a, b))

EPOCH 20 - MSE: 1.1415 --- a: 1.74 --- b: -0.75
EPOCH 40 - MSE: 0.2881 --- a: 2.37 --- b: -1.37
EPOCH 60 - MSE: 0.0728 --- a: 2.69 --- b: -1.68
EPOCH 80 - MSE: 0.0184 --- a: 2.84 --- b: -1.84
EPOCH 100 - MSE: 0.0046 --- a: 2.92 --- b: -1.92
EPOCH 120 - MSE: 0.0012 --- a: 2.96 --- b: -1.96
EPOCH 140 - MSE: 0.0003 --- a: 2.98 --- b: -1.98
EPOCH 160 - MSE: 0.0001 --- a: 2.99 --- b: -1.99
EPOCH 180 - MSE: 0.0000 --- a: 2.99 --- b: -1.99
EPOCH 200 - MSE: 0.0000 --- a: 3.00 --- b: -2.00
